
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

required = [
    "k8s.io/code-generator/cmd/client-gen",
    "k8s.io/code-generator/cmd/deepcopy-gen",
    "github.com/bazelbuild/buildtools/buildozer",
    "github.com/bazelbuild/buildtools/buildifier"
]

[prune]
  non-go = true
  go-tests = true

[[override]]
  branch = "release-1.10" # correct branch
  name = "k8s.io/code-generator"

[[constraint]]
  branch = "master" # latest
  name = "github.com/bazelbuild/buildtools"

[[override]]
  revision = "01a732e01d00cb9a81bb0ca050d3e6d2b947927b" # from 1.10 branch
  name = "k8s.io/gengo"

[[constraint]]
  branch = "master" # I want the latest commit from this branch, not just the latest tag or the version used by client-go.
  name = "github.com/stretchr/testify"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.10" # correct branch

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.10" # correct branch

[[override]]
  name = "k8s.io/client-go"
  branch = "release-7.0" # correct branch

[[override]]
  name = "k8s.io/api"
  branch = "release-1.10" # correct branch
